import React, { useRef, useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { Upload, X, Image as ImageIcon, AlertCircle, Check, Move, GripVertical, ArrowRightLeft, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { api } from "../lib/apiClient";

// Per-image hard cap. Matches the backend `IMAGE_UPLOAD_MAX_BYTES`
// in `/api/sell/image-upload` — feedback is immediate and consistent.
// Originals are uploaded as-is (no client compression) so the user keeps
// full EXIF + colour fidelity. AVIF/WebP variants are generated by the
// backend optimization queue.
const MAX_IMG_BYTES = 5 * 1024 * 1024;          // 5 MB per file
const MAX_LISTING_BYTES = 120 * 1024 * 1024;    // 120 MB total per listing
const LONG_PRESS_MS = 220;

// Shared pointer-drag state across all uploader instances (cross-category drag)
const pointerState = {
  active: false,
  startX: 0, startY: 0,
  category: null, idx: null,
  ghost: null,
  longPressTimer: null,
  lastTargetSlot: null,       // [category, idx] of currently-highlighted slot
  onDropResolver: null,
};

function clearGhost() {
  if (pointerState.ghost) {
    pointerState.ghost.remove();
    pointerState.ghost = null;
  }
}

function clearTargetHighlight() {
  document.querySelectorAll('[data-drag-target="true"]').forEach((el) => {
    el.removeAttribute("data-drag-target");
  });
}

export default function ImageUploader({
  images = [],
  onChange,
  max = 8,
  min = 0,
  label,
  helper,
  testId = "image-uploader",
  category,
  onMoveBetween,
  availableCategories = [],
  // Optional callback used by parent (e.g. SellPage) to report cumulative
  // bytes across ALL uploaders for a single listing — needed to enforce the
  // 120 MB total-listing budget across categorised buckets.
  totalBudgetBytes = MAX_LISTING_BYTES,
  currentTotalBytes = 0,
}) {
  const { t } = useTranslation();
  const ref = useRef(null);
  const [dragOverIdx, setDragOverIdx] = useState(null);
  const [dragOverGrid, setDragOverGrid] = useState(false);
  const [menuOpen, setMenuOpen] = useState(null);
  const [touchDragging, setTouchDragging] = useState(false);
  // Per-file upload progress: { [tempId]: { name, pct, error? } }
  const [uploads, setUploads] = useState({});

  // Cleanup on unmount
  useEffect(() => () => { clearGhost(); clearTargetHighlight(); }, []);

  // -----------------------------------------------------------------------
  // Upload pipeline (no client-side compression).
  //
  // We send originals straight to /api/sell/image-upload. The backend
  // validates magic bytes, stores the original on disk, and enqueues
  // AVIF/WebP/JPG variant generation in the background. The endpoint
  // returns immediately with the public URL — the user sees their photo
  // straight away while the queue catches up off-band.
  //
  // HEIC handling: iPhones default to HEIC, which Chrome / Firefox cannot
  // decode at all. We convert HEIC → JPEG client-side via lazy-loaded
  // libheif WASM (~1 MB, only downloaded when actually needed). After
  // conversion the file is treated like any JPEG.
  // -----------------------------------------------------------------------

  // Detect HEIC/HEIF — iPhones save in this format by default and only
  // Safari can decode it natively.
  const isHeicFile = (file) => {
    const t = (file.type || "").toLowerCase();
    if (t.includes("heic") || t.includes("heif")) return true;
    const n = (file.name || "").toLowerCase();
    return /\.heic$|\.heif$/.test(n);
  };

  // Convert HEIC → JPEG Blob using the libheif WASM bundle.
  const convertHeicToJpegFile = async (file) => {
    const { default: heic2any } = await import("heic2any");
    const out = await heic2any({ blob: file, toType: "image/jpeg", quality: 0.9 });
    const blob = Array.isArray(out) ? out[0] : out;
    const newName = (file.name || "image").replace(/\.(heic|heif)$/i, ".jpg");
    return new File([blob], newName, { type: "image/jpeg" });
  };

  const uploadOne = async (file, tempId) => {
    // Track progress via XMLHttpRequest — axios in api client supports
    // onUploadProgress but the shared instance is configured for JSON.
    // Using XHR here keeps the multipart path simple and lets us update
    // a per-file progress bar in real time.
    const fd = new FormData();
    fd.append("file", file, file.name);
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open("POST", `${api.defaults.baseURL.replace(/\/$/, "")}/sell/image-upload`);
      xhr.withCredentials = true;
      // CSRF cookie is auto-attached; X-CSRF-Token from api defaults.
      const csrf = api.defaults.headers?.common?.["X-CSRF-Token"];
      if (csrf) xhr.setRequestHeader("X-CSRF-Token", csrf);
      xhr.upload.onprogress = (e) => {
        if (!e.lengthComputable) return;
        const pct = Math.round((e.loaded / e.total) * 100);
        setUploads((u) => ({ ...u, [tempId]: { ...(u[tempId] || {}), pct } }));
      };
      xhr.onload = () => {
        if (xhr.status >= 200 && xhr.status < 300) {
          try { resolve(JSON.parse(xhr.responseText)); }
          catch (e) { reject(new Error("Невалиден отговор от сървъра.")); }
        } else {
          let msg = "Грешка при качване.";
          try { msg = JSON.parse(xhr.responseText)?.detail || msg; } catch {}
          reject(new Error(msg));
        }
      };
      xhr.onerror = () => reject(new Error("Мрежова грешка."));
      xhr.ontimeout = () => reject(new Error("Таймаут при качване."));
      xhr.send(fd);
    });
  };

  const handleFiles = async (files) => {
    const fmt = (n) => `${(n / 1024 / 1024).toFixed(1)} MB`;
    const arr = Array.from(files);
    const slotsLeft = Math.max(0, max - images.length);
    if (arr.length > slotsLeft) {
      toast.warning(t("uploader.too_many", { max }));
    }

    let runningTotal = currentTotalBytes;
    const queued = arr.slice(0, slotsLeft);
    // Reserve slot order — uploads happen in parallel but inserts respect
    // user-picked sequence so reordering after the fact isn't necessary.
    const reservations = queued.map((f) => ({
      file: f,
      tempId: `up-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    }));

    const accepted = [];
    for (const { file: f, tempId } of reservations) {
      // 1) Raw per-file size check (fast path before any IO)
      if (f.size > MAX_IMG_BYTES) {
        toast.error(t("uploader.image_too_large", {
          name: f.name, size: fmt(f.size), max: "5 MB",
        }));
        continue;
      }
      // 2) Listing-total budget check (conservative — uses raw bytes)
      if (runningTotal + f.size > totalBudgetBytes) {
        toast.error(t("uploader.total_too_large", {
          current: fmt(runningTotal), incoming: fmt(f.size), max: "120 MB",
        }));
        break;
      }

      let inputFile = f;
      try {
        if (isHeicFile(f)) {
          const tid = toast.loading(
            t("uploader.heic_converting", "Конвертирам {{name}} от HEIC към JPEG…", { name: f.name })
          );
          try { inputFile = await convertHeicToJpegFile(f); }
          finally { toast.dismiss(tid); }
          // Re-check size after HEIC → JPEG conversion (JPEG is usually
          // smaller, but extremely high-bit-depth HEICs can grow).
          if (inputFile.size > MAX_IMG_BYTES) {
            toast.error(t("uploader.image_too_large", {
              name: f.name, size: fmt(inputFile.size), max: "5 MB",
            }));
            continue;
          }
        }
      } catch (e) {
        toast.error(t(
          "uploader.heic_unsupported",
          "{{name}} е HEIC формат, който браузърът ви не може да обработи. На iPhone превключете Settings → Camera → Formats → Most Compatible или конвертирайте към JPG.",
          { name: f.name }
        ));
        continue;
      }

      // Show a 0% placeholder right away so the user knows the upload started.
      setUploads((u) => ({ ...u, [tempId]: { name: f.name, pct: 0 } }));

      try {
        const res = await uploadOne(inputFile, tempId);
        accepted.push(res.url);
        runningTotal += inputFile.size;
        setUploads((u) => { const c = { ...u }; delete c[tempId]; return c; });
      } catch (e) {
        setUploads((u) => ({ ...u, [tempId]: { ...(u[tempId] || {}), error: e.message } }));
        toast.error(e.message || t("uploader.decode_failed", { name: f.name }));
      }
    }

    if (accepted.length) onChange([...images, ...accepted]);
  };

  const remove = (idx) => onChange(images.filter((_, i) => i !== idx));

  const reorder = (fromIdx, toIdx) => {
    if (fromIdx === toIdx || toIdx == null) return;
    const next = [...images];
    const [item] = next.splice(fromIdx, 1);
    next.splice(toIdx, 0, item);
    onChange(next);
  };

  // ===== HTML5 drag (desktop) =====
  const onDragStart = (e, idx) => {
    e.dataTransfer.effectAllowed = "move";
    const payload = JSON.stringify({ category, idx });
    e.dataTransfer.setData("application/x-image-move", payload);
    e.dataTransfer.setData("text/plain", payload);
    // Scroll-lock the page during desktop drag to avoid the surrounding
    // form scrolling under the cursor when the browser's edge-scroll
    // engages — that fights the user's reorder intent and feels janky.
    // Restored unconditionally on dragend (fires for both drop & cancel).
    document.body.style.overflow = "hidden";
  };
  const onDragEndAny = () => {
    document.body.style.overflow = "";
    setDragOverIdx(null);
    setDragOverGrid(false);
  };
  const parseDrag = (e) => {
    try {
      const raw = e.dataTransfer.getData("application/x-image-move") || e.dataTransfer.getData("text/plain");
      if (!raw) return null;
      const d = JSON.parse(raw);
      if (typeof d !== "object" || !d.category) return null;
      return d;
    } catch { return null; }
  };
  const onSlotDragOver = (e, idx) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = "move";
    setDragOverIdx(idx);
  };
  const onSlotDrop = (e, toIdx) => {
    e.preventDefault();
    setDragOverIdx(null); setDragOverGrid(false);
    const d = parseDrag(e); if (!d) return;
    if (d.category === category) reorder(d.idx, toIdx);
    else if (onMoveBetween) onMoveBetween(d.category, d.idx, category, toIdx);
  };
  const onGridDragOver = (e) => {
    if (e.dataTransfer.types.includes("application/x-image-move") || e.dataTransfer.types.includes("text/plain")) {
      e.preventDefault();
      setDragOverGrid(true);
    }
  };
  const onGridDrop = (e) => {
    e.preventDefault();
    setDragOverGrid(false);
    const d = parseDrag(e); if (!d) return;
    if (d.category !== category && onMoveBetween) onMoveBetween(d.category, d.idx, category, null);
  };

  // ===== Touch drag (mobile) =====
  const onTouchStart = (e, idx, src) => {
    if (e.touches.length !== 1) return;
    const t = e.touches[0];
    pointerState.startX = t.clientX;
    pointerState.startY = t.clientY;
    pointerState.category = category;
    pointerState.idx = idx;
    pointerState.active = false;

    if (pointerState.longPressTimer) clearTimeout(pointerState.longPressTimer);
    pointerState.longPressTimer = setTimeout(() => {
      // Enter drag mode — create floating ghost
      pointerState.active = true;
      setTouchDragging(true);
      // Haptic (Android/iOS best-effort)
      try { if (navigator.vibrate) navigator.vibrate(12); } catch {}

      const ghost = document.createElement("div");
      ghost.style.cssText = `position:fixed;left:0;top:0;width:120px;height:90px;background-image:url("${src.replace(/"/g, '\\"')}");background-size:cover;background-position:center;border-radius:8px;box-shadow:0 12px 32px rgba(0,0,0,.35);pointer-events:none;z-index:9999;transform:translate(${pointerState.startX - 60}px, ${pointerState.startY - 45}px) scale(1.05);transition:transform .05s linear;border:2px solid hsl(158 60% 30%);`;
      document.body.appendChild(ghost);
      pointerState.ghost = ghost;
      // Prevent page scroll while dragging
      document.body.style.overflow = "hidden";
      document.body.style.touchAction = "none";
    }, LONG_PRESS_MS);
  };

  const onTouchMove = (e) => {
    if (!pointerState.longPressTimer && !pointerState.active) return;
    const t = e.touches[0];
    const dx = t.clientX - pointerState.startX;
    const dy = t.clientY - pointerState.startY;

    // If user moves before long-press timer fires → cancel (treat as scroll)
    if (!pointerState.active) {
      if (Math.abs(dx) > 8 || Math.abs(dy) > 8) {
        clearTimeout(pointerState.longPressTimer);
        pointerState.longPressTimer = null;
      }
      return;
    }

    // Active drag
    e.preventDefault();
    if (pointerState.ghost) {
      pointerState.ghost.style.transform = `translate(${t.clientX - 60}px, ${t.clientY - 45}px) scale(1.05)`;
    }
    // Find target slot under finger
    const el = document.elementFromPoint(t.clientX, t.clientY);
    clearTargetHighlight();
    pointerState.lastTargetSlot = null;
    if (el) {
      const slot = el.closest("[data-uploader-slot]");
      if (slot) {
        slot.setAttribute("data-drag-target", "true");
        pointerState.lastTargetSlot = {
          cat: slot.getAttribute("data-uploader-category"),
          idx: parseInt(slot.getAttribute("data-uploader-idx"), 10),
        };
      } else {
        const grid = el.closest("[data-uploader-grid]");
        if (grid) {
          grid.setAttribute("data-drag-target", "true");
          pointerState.lastTargetSlot = {
            cat: grid.getAttribute("data-uploader-category"),
            idx: null,
          };
        }
      }
    }

    // Auto-scroll near viewport edges
    const margin = 60;
    if (t.clientY < margin) window.scrollBy(0, -8);
    else if (t.clientY > window.innerHeight - margin) window.scrollBy(0, 8);
  };

  const onTouchEnd = () => {
    if (pointerState.longPressTimer) clearTimeout(pointerState.longPressTimer);
    pointerState.longPressTimer = null;
    if (!pointerState.active) return;

    const target = pointerState.lastTargetSlot;
    const src = pointerState.category;
    const fromIdx = pointerState.idx;
    clearGhost();
    clearTargetHighlight();
    document.body.style.overflow = "";
    document.body.style.touchAction = "";
    pointerState.active = false;
    setTouchDragging(false);

    if (target && src) {
      if (target.cat === src) {
        if (target.idx != null && target.idx !== fromIdx) reorder(fromIdx, target.idx);
      } else if (onMoveBetween) {
        onMoveBetween(src, fromIdx, target.cat, target.idx);
      }
    }
  };

  const onTouchCancel = () => onTouchEnd();

  const moveToOther = (idx, targetCatId) => {
    setMenuOpen(null);
    if (onMoveBetween) onMoveBetween(category, idx, targetCatId, null);
  };

  const meetsMin = images.length >= min;

  return (
    <div
      data-testid={testId}
      className={`rounded-card border bg-white p-4 transition ${dragOverGrid ? "border-[hsl(var(--accent))] ring-2 ring-[hsl(var(--accent))]/20" : "border-[hsl(var(--line))]"}`}
    >
      {label && (
        <div className="flex items-center justify-between mb-3 gap-3 flex-wrap">
          <div>
            <div className="text-sm font-semibold">{label}</div>
            {helper && <div className="text-xs text-[hsl(var(--ink-muted))] mt-0.5">{helper}</div>}
          </div>
          <div className={`flex items-center gap-1.5 text-xs font-mono ${meetsMin ? "text-[hsl(var(--accent))]" : "text-[hsl(var(--ink-muted))]"}`}>
            {meetsMin ? <Check size={12} /> : <AlertCircle size={12} />}
            {images.length}/{max} {min > 0 && <span>· {t("common.min_short")} {min}</span>}
          </div>
        </div>
      )}

      <div
        className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2.5"
        data-uploader-grid="true"
        data-uploader-category={category}
        onDragOver={onGridDragOver}
        onDrop={onGridDrop}
        onDragLeave={() => setDragOverGrid(false)}
      >
        {images.map((src, i) => (
          <div
            key={i}
            draggable
            onDragStart={(e) => onDragStart(e, i)}
            onDragOver={(e) => onSlotDragOver(e, i)}
            onDragLeave={() => setDragOverIdx(null)}
            onDrop={(e) => onSlotDrop(e, i)}
            onDragEnd={onDragEndAny}
            onTouchStart={(e) => onTouchStart(e, i, src)}
            onTouchMove={onTouchMove}
            onTouchEnd={onTouchEnd}
            onTouchCancel={onTouchCancel}
            data-uploader-slot="true"
            data-uploader-category={category}
            data-uploader-idx={i}
            className={`relative aspect-[4/3] rounded-md border overflow-hidden bg-[hsl(var(--surface))] cursor-move select-none transition ${dragOverIdx === i ? "border-[hsl(var(--accent))] ring-2 ring-[hsl(var(--accent))]/30" : "border-[hsl(var(--line))]"} data-[drag-target=true]:border-[hsl(var(--accent))] data-[drag-target=true]:ring-2 data-[drag-target=true]:ring-[hsl(var(--accent))]/40`}
            data-testid={`${testId}-slot-${i}`}
            style={{ touchAction: "pan-y" }}
          >
            <img src={src} alt="" className="w-full h-full object-cover pointer-events-none" draggable="false" />
            <div className="absolute top-1 left-1 bg-black/60 text-white rounded px-1.5 py-0.5 flex items-center gap-1 text-[10px] font-mono pointer-events-none">
              <GripVertical size={10} /> {i + 1}
            </div>
            <div className="absolute top-1 right-1 flex flex-col gap-1">
              <button
                type="button"
                onClick={() => remove(i)}
                className="bg-white/90 rounded-full p-1 border border-[hsl(var(--line))] hover:bg-[hsl(var(--danger))] hover:text-white transition"
                data-testid={`${testId}-remove-${i}`}
              ><X size={12} /></button>
              {availableCategories.length > 0 && (
                <button
                  type="button"
                  onClick={() => setMenuOpen(menuOpen === i ? null : i)}
                  className="bg-white/90 rounded-full p-1 border border-[hsl(var(--line))] hover:bg-[hsl(var(--ink))] hover:text-white transition"
                  data-testid={`${testId}-move-${i}`}
                  title="Премести в друга категория"
                ><ArrowRightLeft size={12} /></button>
              )}
            </div>
          </div>
        ))}
        {/* In-progress upload tiles — show one placeholder per file
            currently uploading, with a thin progress bar at the bottom.
            Failed uploads stick around with an error pill so the user
            knows what to retry; clicking dismisses the failure tile. */}
        {Object.entries(uploads).map(([tid, u]) => (
          <div
            key={tid}
            className="relative aspect-[4/3] rounded-md border border-[hsl(var(--line))] overflow-hidden bg-[hsl(var(--surface))] flex flex-col items-center justify-center gap-2"
            data-testid={`${testId}-uploading-${tid}`}
          >
            {u.error ? (
              <>
                <AlertCircle size={20} className="text-[hsl(var(--danger))]" />
                <div className="text-[10px] text-[hsl(var(--danger))] px-2 text-center truncate w-full">{u.error}</div>
                <button
                  type="button"
                  onClick={() => setUploads((m) => { const c = { ...m }; delete c[tid]; return c; })}
                  className="text-[10px] underline text-[hsl(var(--ink-muted))]"
                >Премахни</button>
              </>
            ) : (
              <>
                <Loader2 size={20} className="text-[hsl(var(--ink-muted))] animate-spin" />
                <div className="text-[10px] text-[hsl(var(--ink-muted))] truncate max-w-[90%]">{u.name}</div>
                <div className="absolute bottom-0 left-0 right-0 h-1 bg-[hsl(var(--line))]">
                  <div
                    className="h-full bg-[hsl(var(--accent))] transition-[width]"
                    style={{ width: `${Math.max(2, u.pct || 0)}%` }}
                  />
                </div>
              </>
            )}
          </div>
        ))}
        {images.length < max && (
          <button
            type="button"
            onClick={() => ref.current?.click()}
            className="aspect-[4/3] rounded-md border-2 border-dashed border-[hsl(var(--line))] hover:border-[hsl(var(--ink))] transition flex flex-col items-center justify-center gap-1.5 text-[hsl(var(--ink-muted))] hover:text-[hsl(var(--ink))]"
            data-testid={`${testId}-add`}
          >
            <Upload size={18} />
            <span className="text-[11px]">{t("forms.add", "Добави")}</span>
          </button>
        )}
      </div>
      <input ref={ref} type="file" accept="image/*,.heic,.heif" multiple className="hidden" onChange={(e) => handleFiles(e.target.files)} data-testid={`${testId}-input`} />

      {menuOpen != null && (
        <>
          <div className="fixed inset-0 z-40 bg-black/40" onClick={() => setMenuOpen(null)} data-testid={`${testId}-menu-overlay`} />
          <div className="fixed left-0 right-0 bottom-0 sm:left-auto sm:right-6 sm:bottom-6 sm:w-72 z-50 bg-white rounded-t-xl sm:rounded-xl shadow-2xl border border-[hsl(var(--line))] overflow-hidden" data-testid={`${testId}-menu`}>
            <div className="px-5 py-3 border-b border-[hsl(var(--line))] bg-[hsl(var(--surface))]">
              <div className="text-xs text-[hsl(var(--ink-muted))]">Премести снимка #{menuOpen + 1} в:</div>
            </div>
            {availableCategories.map((c) => (
              <button
                key={c.id}
                type="button"
                onClick={() => moveToOther(menuOpen, c.id)}
                className="w-full text-left px-5 py-4 sm:py-3 text-sm hover:bg-[hsl(var(--surface))] border-b border-[hsl(var(--line))] last:border-b-0 flex items-center gap-2"
                data-testid={`${testId}-moveto-${c.id}-${menuOpen}`}
              >
                <ArrowRightLeft size={14} className="text-[hsl(var(--accent))]" /> {c.label}
              </button>
            ))}
            <button
              type="button"
              onClick={() => setMenuOpen(null)}
              className="w-full text-center px-5 py-4 sm:py-3 text-sm text-[hsl(var(--ink-muted))] bg-[hsl(var(--surface))]"
              data-testid={`${testId}-menu-cancel`}
            >Отказ</button>
          </div>
        </>
      )}

      {images.length > 0 && (
        <p className="mt-2 text-[10px] text-[hsl(var(--ink-muted))] flex items-center gap-1">
          <Move size={9} /> Натиснете и задръжте, за да преместите снимка
        </p>
      )}
      {touchDragging && <p className="sr-only" data-testid={`${testId}-touch-dragging`}>dragging</p>}
    </div>
  );
}
